### ISSUE TITLE
[Bug]: Invalid "var-use-before-def", 101 flagging variable in a CATCH block

### ISSUE THREAD

**Issue by HGS-jimpendleton** [interactive-data-language/vscode-idl#21] opened 2024-01-30 17:18 UTC
### Current Behavior

In the following snippet, the variable "tmpDir" is being flagged by the IDL plug-in as being used before its definition.  However, the runtime syntax manages this state and the plug-in's pre-compiler should not flag it.

catch, err
  if err ne 0 then begin
    catch, /cancel
    if lun gt 0 then free_lun, lun
    if file_test(tmpDir) then file_delete, tmpDir, /recursive
    return, retval
  endif
  
  if strlen(basename) gt 255 then return, 0
  if strpos(basename, path_sep()) ne -1 then return, 0
  tmpDir = self->UnusedFile('tmp')

### Expected Behavior

The plug-in is WAY too verbose (and I've turned off as many switches as I have found) as it is and shouldn't be flagging valid logic. 

### Steps to Reproduce

Cut and paste the example code.

### Operating System

- [ ] macOS (Intel x86_64)
- [ ] macOS (ARM64)
- [ ] Linux
- [X] Windows

### IDL Version

9.0

**Comment by znorman-harris** [comment] 2024-02-05 18:02
I'm going to close this one as won't fix.

This also is not a bug - it's a design decision. Technically, in your catch block, you are using variables that have *not* been defined. And it is property reporting that.

One thing we have internally talked about, is how to organize your code to follow better to-down definition and usage examples.

See this from our docs for more details:

https://interactive-data-language.github.io/vscode-idl/problem-codes/codes/101.html#catch-blocks

**Closed by znorman-harris** 2024-02-05 18:02 UTC
Labels: type: bug
