### ISSUE TITLE
[Bug]: Auto left-tab when typing "end"

### ISSUE THREAD

**Issue by HGS-davidstreutker** [interactive-data-language/vscode-idl#11] opened 2023-10-13 20:40 UTC
### Current Behavior

Auto-indent triggers left-tab when typing `end`, even for a variable name (e.g. `endmember` or `endian`) or typing in a comment.  This occurs both in the editor and notebooks.

### Expected Behavior

Possibly stricter left-tab rule when typing:

- ignore comments
- require a space after `end`, `endfor`, `endif`, etc.
- alternatively, new feature to auto-complete logic blocks similar to the Eclipse IDLDE

### Steps to Reproduce

1. Indent one tab
2. Type `end`

### Operating System

- [ ] macOS (Intel x86_64)
- [ ] macOS (ARM64)
- [ ] Linux
- [X] Windows

### IDL Version

IDL 9.0 (test)

**Comment by znorman-harris** [comment] 2023-10-24 02:49
Hmm, this is a tricky one. Doing some testing, it's pretty easy to reproduce this issue within VSCode. Unfortunately, I don't think there's anything we can do to fix this one. 

The regular expressions for reducing indentations are very specific already (you can find them [here](https://github.com/interactive-data-language/vscode-idl/blob/0e7df98538e12c70c8ac5eef767f96115bfbb6d3/libs/vscode/client/src/lib/language-configuration.interface.ts#L36)). There are two reasons that a reduction in indentation seems to happen:

1. The rule specified in the link above triggers "end" as you are typing your variable name "endsomethingelse". 
2. We also have bracket pairs and, typing the closing of the bracket pair, seems to reduce indentation.

Because of the second one, I'm not sure there's a great path forward here. I think it's nice to see the outlines around terms like "pro", "begin", and "end" like other languages have so I don't want to take that out completely.

About the only thing I can think of is to use auto-complete after you type "en" which should show the variables you can use. I guess if you are using the formatter it will take care of it for you, but that's not everyone's cup of tea.

I did remove the "end" from the reduce indentation rules, but the issue will still persist because of the bracket pairs.

**Comment by znorman-harris** [comment] 2023-10-31 00:22
After giving this a few weeks, marking as "wontfix" because we have to disable useful functionality to fix the auto-indent logic at this point in time.

If anyone else is annoyed by this, feel free to re-open and add a comment!

**Closed by znorman-harris** 2023-10-31 00:22 UTC
Labels: type: bug, wontfix
