### ISSUE TITLE
[Bug]: Invalid "ptr-de-ref-illegal", 94 when dereferencing member variable in ternary

### ISSUE THREAD

**Issue by liamw1** [interactive-data-language/vscode-idl#42] opened 2024-09-06 19:39 UTC
### Current Behavior

Valid member variable dereference will be flagged as an error when used in a ternary.

### Expected Behavior

No error should appear

### Steps to Reproduce

1. Create a struct with two ptr member variables
2. Write a function which uses a ternary to decide which variable to dereference
3. Observe the error generated

Example code:

```
pro TestClass__define
  !null = {TestClass, foo:ptr_new(), bar:ptr_new()}
end

function TestClass::init, value
  self.foo = ptr_new(0)
  self.bar = ptr_new(value)
  return, 1
end

function TestClass::get, which
  retval = which eq "foo" ? *self.foo : *self.bar

  return, retval
end

pro test
  compile_opt idl2

  class = obj_new('TestClass', 1)
  print, class.get("bar")
end
```

### Operating System

- [ ] macOS (Intel x86_64)
- [ ] macOS (ARM64)
- [ ] Linux
- [X] Windows

### IDL Version

8.9

**Comment by znorman-harris** [comment] 2024-09-09 02:02
Thanks for the reproduce! I fixed this issue which was because we were "exiting" the ternary operator before the property in the second half of the statement. 

Will be included in the next release.

**Closed by znorman-harris** 2024-09-09 02:02 UTC
Labels: type: bug
